---
title: "Exploration"
author: "Carlo Provinciali"
date: "March 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
restaurants_by_cuisine <- read.csv("C:/Users/Carlo/Desktop/EDAV Project/number of restaurants by cuisine.csv")
```

```{r}
library(tidyverse)

r_by_city <- restaurants_by_cuisine %>% group_by(city, state) %>%
                    summarize(number= sum(NumberOfRestaurants)) %>%
                    filter(number > 1000)

ggplot(r_by_city, aes(x = city, y = number))+
  geom_col()
```

```{r}
top_cities <- c("Charlotte",
                "Las Vegas",
                "Mississauga",
                "Montréal",
                "Phoenix",
                "Pittsburgh",
                "Scottsdale",
                "Toronto")

tc <- restaurants_by_cuisine %>% filter(city %in% top_cities)

#ggplot(tc, aes(x = city, y = NumberOfRestaurants))+
#  geom_col(color = aes(category))
```

```{r}
toronto <- restaurants_by_cuisine %>% filter(city == "Toronto")


ggplot(toronto, aes(x = reorder(category, NumberOfRestaurants), y = NumberOfRestaurants)) +
  geom_col()+
  coord_flip()+
  scale_y_continuous(breaks = seq(0, 650, 50))
```

