---
title: "Exploration"
author: "Carlo Provinciali"
date: "March 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)

restaurants_by_cuisine <- read_csv("~/Data/number of restaurants by cuisine.csv")
```

```{r}
library(tidyverse)

r_by_city <- restaurants_by_cuisine %>% group_by(city, state) %>%
                    summarize(number= sum(NumberOfRestaurants)) %>%
                    filter(number > 1000)

ggplot(r_by_city, aes(x = city, y = number))+
  geom_col()
```

```{r}
top_cities <- c("Charlotte",
                "Las Vegas",
                "Mississauga",
                "Montréal",
                "Phoenix",
                "Pittsburgh",
                "Scottsdale",
                "Toronto")

tc <- restaurants_by_cuisine %>% filter(city %in% top_cities)

#ggplot(tc, aes(x = city, y = NumberOfRestaurants))+
#  geom_col(color = aes(category))
```

```{r}
toronto <- restaurants_by_cuisine %>% filter(city == "Toronto")


ggplot(toronto, aes(x = reorder(category, NumberOfRestaurants), y = NumberOfRestaurants)) +
  geom_col()+
  coord_flip()+
  scale_y_continuous(breaks = seq(0, 650, 50))
```

```{r}
restaurants_in_Toronto <- read_csv("restaurants in Toronto.csv")

by_category <- restaurants_in_Toronto %>% group_by(category) %>%
                summarize(count = n()) %>%
                arrange(desc(count))

ggplot(by_category[1:50,], aes(reorder(category, count), count))+
  geom_col()+
  scale_y_continuous(breaks = seq(0, 1200, 50))+
  coord_flip()+
  ggtitle("Categories of Restaurants in Toronto")

```

```{r}
categories = c('American (New)',
		'American (Traditional)',
		'Asian Fusion',
		'Cajun/Creole',
		'Canadian (New)',
		'Cantonese',
		'Caraibbean',
		'Chinese',
		'Cuban',
		'Ethiopian',
		'French',
		'Greek',
		'Halal',
		'Indian',
		'Indonesian',
		'Italian',
		'Japanese',
		'Korean',
		'Malaysian',
		'Mexican',
		'Middle Eastern',
		'Pakistani',
		'Peruvian',
		'Singaporean',
		'Syrian',
		'Thai',
		'Turkish',
		'Vietnamese')

```


```{r}
neighborhood <- restaurants_in_Toronto %>%
                    filter(category %in% categories) %>%
                    group_by(neighborhood) %>%
                    summarize(count =n()) %>%
                    arrange(desc(count))

zipcode <- neighborhood <- restaurants_in_Toronto %>%
                    filter(category %in% categories) %>%
                    group_by(postal_code) %>%
                    summarize(count =n()) %>%
                    arrange(desc(count))
```


```{r}

pop_neighborhood <- restaurants_in_Toronto %>%
                    filter(category %in% categories) %>%
                    group_by(neighborhood) %>%
                    mutate(neigh_pop =n()) %>%
                    filter(neigh_pop >=10) %>%
                    ungroup() %>%
                    filter(neigh_pop >= 70) %>%
                    group_by(neighborhood, category) %>%
                    summarize(count = n())

ggplot(pop_neighborhood, aes(x = category, y = count))+
  geom_col(aes(fill = category))+
  coord_flip()+
  facet_wrap(~neighborhood)

```



